export const UserLoginProcessStatus = {

		AUTHENTICATING: "AUTHENTICATING",
		AUTHENTICATED: "AUTHENTICATED",
		AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",

		USER_ACCOUNT_CREATING: "USER_ACCOUNT_CREATING",
		USER_ACCOUNT_CREATED: "USER_ACCOUNT_CREATED",
		USER_ACCOUNT_CREATION_ERROR: "USER_ACCOUNT_CREATION_ERROR",

		BACK_TO_LOGIN: "BACK_TO_LOGIN",
		USER_LOGGING_OUT: "USER_LOGGING_OUT",
		USER_LOGGED_OUT: "USER_LOGGED_OUT",
		
		RESENDING_VARIFICATION: "RESENDING_VARIFICATION",
		RESENT_VARIFICATION: "RESENT_VARIFICATION",
		EMAIL_VARIFIED: "EMAIL_VARIFIED",
		EMAIL_NOT_VARIFIED: "EMAIL_NOT_VARIFIED",
		
		LOGIN_EMAIL_INPUT: "LOGIN_EMAIL_INPUT",
		LOGIN_PASSWORD_INPUT: "LOGIN_PASSWORD_INPUT",

		SHOW_CREATE_ACCOUNT: "SHOW_CREATE_ACCOUNT",
		ENABLE_LOGIN: "ENABLE_LOGIN"

}

export const UserDataLoadingProcessStatus = {

	REQUESTING_USER_PROFILE_DATA: "REQUESTING_USER_PROFILE_DATA",
	USER_PROFILE_DATA_RECEIVED: "USER_PROFILE_DATA_RECEIVED",
	UPDATING_USER_PROFILE_DATA: "UPDATING_USER_PROFILE_DATA",
	USER_PROFILE_DATA_UPDATED: "USER_PROFILE_DATA_UPDATED",
	
}

export const UserDataActionType = {
	SET_USER_GENDER: "SET_USER_GENDER",
	SET_USER_DISPLAY_NAME: "SET_USER_DISPLAY_NAME",
	SET_USER_BIRTHDAY: "SET_USER_BIRTHDAY",

	REQUESTING_USER_PROFILE_DATA: "REQUESTING_USER_PROFILE_DATA",
	USER_PROFILE_DATA_RECEIVED: "USER_PROFILE_DATA_RECEIVED",
	USER_PROFILE_DATA_RECEIVING_ERROR: "USER_PROFILE_DATA_RECEIVING_ERROR",

	UPDATING_USER_PROFILE_DATA: "UPDATING_USER_PROFILE_DATA",
	USER_PROFILE_DATA_UPDATED: "USER_PROFILE_DATA_UPDATED",
	USER_PROFILE_DATA_UPDATING_ERROR: "USER_PROFILE_DATA_UPDATING_ERROR"
}